version: 0.2

env:
  variables:
    INDEX_FN: index-photos
    SEARCH_FN: search-photos

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - set -e
      - mkdir -p dist
      # Zip each Lambda from your backend folder
      - zip -j dist/index-photos.zip backend/LF1.py
      - zip -j dist/search-photos.zip backend/LF2.py
  post_build:
    commands:
      - aws lambda update-function-code --function-name "$INDEX_FN"   --zip-file fileb://dist/index-photos.zip
      - aws lambda update-function-code --function-name "$SEARCH_FN"  --zip-file fileb://dist/search-photos.zip

artifacts:
  files:
    - dist/**/*